import type { NextPage } from 'next';
import Head from 'next/head';
import Button from '../components/Button';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Title</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Button>Click me!</Button>
				<Button color='red'>Click me!</Button>
				<Button color='purple'>Click me!</Button>
				<Button color='green'>Click me!</Button>
			</main>

			<footer></footer>
		</div>
	);
};

export default Home;
